version: '3.8'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/src/redmine/files:cached

  redmine:
    build:
      context: ./docker
      dockerfile: centos.Dockerfile
    restart: on-failure
    volumes:
      - ./www:/usr/src/redmine/files:cached

  mariadb:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql:delegated
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:
  database:
